name: Auto-merge theme updates

on: [pull_request]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Merge pull request
        if: github.actor == 'dependabot[bot]'
        run: gh pr merge '${{ github.event.pull_request.html_url }}' --squash
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

